### ISSUE TITLE
Wrong spec.homepage

### ISSUE THREAD

**Issue by draganm** [mikekelly/yu#5]
There is a typo in the spec.homepage, making it difficult to find this repo when following link from RubGems:
  spec.homepage      = "https://github.com/mikekellly/yu"
should be
  spec.homepage      = "https://github.com/mikekelly/yu"

**Comment by mikekelly** [comment]
good catch, thanks

**Comment by mikekelly** [comment]
just pushing the release now to rubygems

**Comment by mikekelly** [comment]
thanks again :+1:
